configure: use AC_LINK_IFELSE to check __fp16
Clang can compile __fp16 even when it doesn't support it. When we try
link, it will report:
    /usr/bin/ld: lib/.libs/libmpi.so: undefined reference to
`__gnu_h2f_ieee'

Co-authored-by: Ken Raffenetti <raffenet@mcs.anl.gov>