mpl: Use CPU affinity functions with standard names
The functions with leading underscores are internally used in some systems, but
the user-facing ones are without underscores:
https://linux.die.net/man/3/cpu_set.  The underscore-prefixed names are not
available on Musl systems, leading to a linking error:

```
[01:19:03] libtool: link: cc -fvisibility=hidden -DNDEBUG -DNVALGRIND -O3 -o src/env/.libs/mpichversion src/env/mpichversion.o  lib/.libs/libmpi.so -lpthread -lm -Wl,-rpath -Wl,/workspace/destdir/lib
[01:19:03] /opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/8.1.0/../../../../x86_64-linux-musl/bin/ld: lib/.libs/libmpi.so: undefined reference to `__CPU_ISSET_S'
[01:19:03] /opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/8.1.0/../../../../x86_64-linux-musl/bin/ld: lib/.libs/libmpi.so: undefined reference to `__CPU_SET_S'
[01:19:03] /opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/8.1.0/../../../../x86_64-linux-musl/bin/ld: lib/.libs/libmpi.so: undefined reference to `__CPU_ZERO_S'
[01:19:03] /opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/8.1.0/../../../../x86_64-linux-musl/bin/ld: lib/.libs/libmpi.so: undefined reference to collect2: error: ld returned 1 exit status
[01:19:03] `__CPU_ISSET_S'
[01:19:03] /opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/8.1.0/../../../../x86_64-linux-musl/bin/ld: lib/.libs/libmpi.so: undefined reference to `__CPU_SET_S'
[01:19:03] /opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/8.1.0/../../../../x86_64-linux-musl/bin/ld: lib/.libs/libmpi.so: undefined reference to `__CPU_ZERO_S'
[01:19:03] collect2: error: ld returned 1 exit status
[01:19:03] make[2]: *** [Makefile:14129: src/env/mpichversion] Error 1
[01:19:03] make[2]: *** Waiting for unfinished jobs....
[01:19:03] make[2]: *** [Makefile:14135: src/env/mpivars] Error 1
```