ch4: Fix typedefs in workq
The typedefs in the work queue code were causing some warnings that look
like this:

    ./src/mpid/ch4/include/mpidpre.h:509:3: warning: redefinition of typedef 'MPIDI_av_entry_t' is a C11 feature

Signed-off-by: Pavan Balaji <balaji@anl.gov>