strerror: simplify the thread-safe strerror function.
The MPIR_Strerror function is basically a poor man's implementation of
the C11 strerror_s function.  Since we now rely on POSIX 2001, we no
longer need to maintain the older variants of strerror.